service: serverless-email-api

frameworkVersion: '4'

# Enable dotenv support for loading .env file
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  
  # Environment variables - loaded from .env file locally
  environment:
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASS: ${env:EMAIL_PASS}
    NODE_ENV: ${env:NODE_ENV, 'production'}
  
  # API Gateway settings
  apiGateway:
    shouldStartNameWithService: true
  
  # IAM permissions (if you need to access other AWS services)
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
          Resource: '*'

functions:
  sendEmail:
    handler: handler.sendEmail
    timeout: 30  # 30 seconds timeout
    memorySize: 256  # 256 MB memory
    description: Send email via Gmail SMTP
    events:
      - http:
          path: send-email
          method: post
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000
    # This adds IS_OFFLINE environment variable
    useChildProcesses: true