service: serverless-email-api-python

frameworkVersion: '4'

useDotenv: true

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    EMAIL_USER: ${env:EMAIL_USER}
    EMAIL_PASS: ${env:EMAIL_PASS}
    NODE_ENV: ${env:NODE_ENV, 'production'}

functions:
  sendEmail:
    handler: handler.send_email
    timeout: 30
    memorySize: 256
    description: Send email via Gmail SMTP
    events:
      - http:
          path: send-email
          method: post
          cors: true

plugins:
  - serverless-offline
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: false
    slim: true
  serverless-offline:
    httpPort: 3000